// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/v1/Batlle.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BattleRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BattleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BattleRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BattleRequestMultiError, or
// nil if none found.
func (m *BattleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BattleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MonsterA

	// no validation rules for MonsterB

	// no validation rules for Address

	// no validation rules for BattleLevel

	if len(errors) > 0 {
		return BattleRequestMultiError(errors)
	}
	return nil
}

// BattleRequestMultiError is an error wrapping multiple validation errors
// returned by BattleRequest.ValidateAll() if the designated constraints
// aren't met.
type BattleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BattleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BattleRequestMultiError) AllErrors() []error { return m }

// BattleRequestValidationError is the validation error returned by
// BattleRequest.Validate if the designated constraints aren't met.
type BattleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BattleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BattleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BattleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BattleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BattleRequestValidationError) ErrorName() string { return "BattleRequestValidationError" }

// Error satisfies the builtin error interface
func (e BattleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBattleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BattleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BattleRequestValidationError{}

// Validate checks the field values on BattleReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BattleReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BattleReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BattleReplyMultiError, or
// nil if none found.
func (m *BattleReply) ValidateAll() error {
	return m.validate(true)
}

func (m *BattleReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BattleReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BattleReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BattleReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ErrorText

	// no validation rules for Message

	// no validation rules for Result

	if len(errors) > 0 {
		return BattleReplyMultiError(errors)
	}
	return nil
}

// BattleReplyMultiError is an error wrapping multiple validation errors
// returned by BattleReply.ValidateAll() if the designated constraints aren't met.
type BattleReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BattleReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BattleReplyMultiError) AllErrors() []error { return m }

// BattleReplyValidationError is the validation error returned by
// BattleReply.Validate if the designated constraints aren't met.
type BattleReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BattleReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BattleReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BattleReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BattleReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BattleReplyValidationError) ErrorName() string { return "BattleReplyValidationError" }

// Error satisfies the builtin error interface
func (e BattleReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBattleReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BattleReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BattleReplyValidationError{}

// Validate checks the field values on BattleReply_Data with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BattleReply_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BattleReply_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BattleReply_DataMultiError, or nil if none found.
func (m *BattleReply_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *BattleReply_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BattleLevel

	// no validation rules for BpFragmentNum

	// no validation rules for BpPotionNum

	// no validation rules for ChallengeExp

	// no validation rules for ChallengeLevel

	if len(errors) > 0 {
		return BattleReply_DataMultiError(errors)
	}
	return nil
}

// BattleReply_DataMultiError is an error wrapping multiple validation errors
// returned by BattleReply_Data.ValidateAll() if the designated constraints
// aren't met.
type BattleReply_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BattleReply_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BattleReply_DataMultiError) AllErrors() []error { return m }

// BattleReply_DataValidationError is the validation error returned by
// BattleReply_Data.Validate if the designated constraints aren't met.
type BattleReply_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BattleReply_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BattleReply_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BattleReply_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BattleReply_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BattleReply_DataValidationError) ErrorName() string { return "BattleReply_DataValidationError" }

// Error satisfies the builtin error interface
func (e BattleReply_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBattleReply_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BattleReply_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BattleReply_DataValidationError{}
