// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.1

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type GreeterHTTPServer interface {
	GetHello(context.Context, *HelloRequest) (*HelloReply, error)
	GetHelloA(context.Context, *CreateClusterRes) (*CreateClusterRes, error)
	SetHello(context.Context, *HelloRequest) (*CreateClusterRes, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.GET("/hello/{name}", _Greeter_GetHello0_HTTP_Handler(srv))
	r.POST("/hello", _Greeter_SetHello0_HTTP_Handler(srv))
	r.GET("/", _Greeter_GetHelloA0_HTTP_Handler(srv))
}

func _Greeter_GetHello0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/hello.v1.Greeter/GetHello")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHello(ctx, req.(*HelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_SetHello0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/hello.v1.Greeter/SetHello")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetHello(ctx, req.(*HelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateClusterRes)
		return ctx.Result(200, reply)
	}
}

func _Greeter_GetHelloA0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateClusterRes
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/hello.v1.Greeter/GetHelloA")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHelloA(ctx, req.(*CreateClusterRes))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateClusterRes)
		return ctx.Result(200, reply)
	}
}

type GreeterHTTPClient interface {
	GetHello(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *HelloReply, err error)
	GetHelloA(ctx context.Context, req *CreateClusterRes, opts ...http.CallOption) (rsp *CreateClusterRes, err error)
	SetHello(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *CreateClusterRes, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

func (c *GreeterHTTPClientImpl) GetHello(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/hello/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/hello.v1.Greeter/GetHello"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *GreeterHTTPClientImpl) GetHelloA(ctx context.Context, in *CreateClusterRes, opts ...http.CallOption) (*CreateClusterRes, error) {
	var out CreateClusterRes
	pattern := "/"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/hello.v1.Greeter/GetHelloA"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *GreeterHTTPClientImpl) SetHello(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*CreateClusterRes, error) {
	var out CreateClusterRes
	pattern := "/hello"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/hello.v1.Greeter/SetHello"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
