trace:
  endpoint: 114.67.201.131:11800
server:
  http:
    addr: 0.0.0.0:809
    timeout: 60s
  grpc:
    addr: 0.0.0.0:909
    timeout: 60s
  log:
#    path: /var/log/go-west
    path:

data:
  mongodb:
    uri: "mongodb://localhost:27017/"
    database: "cart-db"
  mysql:
    addr: "192.168.50.16:3306"
    dsn: "root:123456@tcp(192.168.50.16:3306)/test?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    readDSN: ["root:123456@tcp(192.168.50.16:3306)/test?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
    active: 10
    idle: 5
    idleTimeout: "4h"
    queryTimeout: "5s"
    execTimeout: "5s"
    tranTimeout: "10s"

  redis:
    name: "go-west"
    proto: "tcp"
    addr: "192.168.50.16:6379"
    dialTimeout: "1s"
    readTimeout: "1s"
    writeTimeout: "1s"
    config:
      active: 100
      idle: 100
      idleTimeout: "3s"

