trace:
  endpoint: 114.67.201.131:11800
server:
  http:
    addr: 0.0.0.0:809
    timeout: 1s
  grpc:
    addr: 0.0.0.0:909
    timeout: 1s
  log:
#    path: /var/log/go-west
    path:

data:
  mongodb:
    uri: "mongodb://localhost:27017/"
    database: "cart-db"
  mysql:
    dsn: "root:123456@tcp(192.168.50.16:3306)/test?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active: 10
    idle: 5
    idleTimeout: "4h"
    queryTimeout: "1200s"
    execTimeout: "1200s"
    tranTimeout: "1200s"